version: "3.1"

services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=letseatinthai
      - MYSQL_USER=letseatinthai
      - MYSQL_PASSWORD=Letseatinthai#2017
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    image: letseatinthai
    depends_on:
      - mariadb
      - redis
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application/:/usr/share/nginx/html
      - ./.env:/usr/share/nginx/html/.env
      - ./service_account.json:/usr/share/key/service_account.json